name: Refresh Pages list

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '1 0 * * SUN'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Commit to the repo
        run: |
          git config --global user.name 'Kevin Li'
          git config --global user.email '102123416+afa5e@users.noreply.github.com'
          git add .
          git commit -am "Update articles list"
          git push